### ISSUE TITLE
難易度: Easy のときに正しい答えを選択できない

### ISSUE THREAD

**Issue by siketyan** [Treasure-Hunting/App#13]
Easy の答えは 2 通り（0, 1）なのに対し，4 通り（00, 01, 10, 11）の選択肢が表示される．

**Comment by siketyan** [comment]
Close by #18

**Comment by raiga0310** [comment]
いまだ表示されないのでリオープン

**Comment by raiga0310** [comment]
if a==b とifequal,ifnotequal試しましたがうまく行きませんね

**Comment by Snowman-s** [comment]
それはエラーが出るのでしょうか？意図した動作をしないのですか？

**Comment by raiga0310** [comment]
エラーではないようです
if a==bでは空白を入れたらエラーは出ませんでしたが

**Comment by Snowman-s** [comment]
どのように意図した動作がされないのですか？(今は何が表示されますか？)
